resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pipeline
  type: git
  source:
    uri: https://github.com/nthomson-pivotal/bosh-stemcell-scanning-aws.git
    branch: master

- name: zookeeper-release
  type: git
  source:
    uri: https://github.com/cppforlife/zookeeper-release.git
    branch: master

- name: tile
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: stemcells
    product_version: 3586.*
    sort_by: semver

- name: schedule
  type: time
  source:
    interval: 5m
    start: "12:00 AM"
    stop: "11:59 PM"
    location: America/Los_Angeles
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

jobs:
- name: regulator
  plan:
  - get: schedule
    trigger: true
  - get: tile
    params: { globs: [] }

- name: main
  public: true
  plan:
  - aggregate:
    - get: pipeline
    - get: zookeeper-release
    - get: pivnet-product
      resource: tile
      passed: [regulator]
      trigger: true
      params:
        globs:
        - "*-aws-*"
  - task: main
    file: pipeline/tasks/main.yml
    params:
      BBL_AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      BBL_AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      BBL_AWS_REGION: {{aws_region}}
