---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.22.0

inputs:
  - name: pipeline
  - name: zookeeper-release
  - name: pivnet-product

params:
  BBL_AWS_ACCESS_KEY_ID:
  BBL_AWS_SECRET_ACCESS_KEY:
  BBL_AWS_REGION:

run:
  path: pipeline/tasks/main
