#!/bin/sh

#set -e

export BBL_IAAS=aws
export BBL_STATE_DIRECTORY=bbl-state

export BOSH_DEPLOYMENT=zookeeper
export BOSH_NON_INTERACTIVE=true

mkdir bbl-state

bbl -n plan

bbl -n up

eval "$(bbl print-env)"

stemcell_file=$(ls pivnet-product/*.tgz)

bosh upload-stemcell $stemcell_file

bosh deploy zookeeper-release/manifests/zookeeper.yml

bosh delete-deployment

bbl -n destroy

